<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_rhino-controls',
		'title' => 'Rhino Controls',
		'fields' => array (
			array (
				'key' => 'field_5602d298977f8',
				'label' => 'Task to run',
				'name' => 'rhino_taskrunner',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'fix-licenses' => 'Fix Licences',
					'onethree-upgrade' => 'Upgrade Rhino 1.3 Options',
					'onethree-downgrade' => 'Reset 1.3 Upgrades',
					'fix-tribe-mayhem' => 'Fix Tribe Subpage Meta',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-zookeeper',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_theme-options',
		'title' => 'Theme Options',
		'fields' => array (
			array (
				'key' => 'field_55c10c3a85bbf',
				'label' => 'General',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_564b7ad18471c',
				'label' => 'Enable 1.3 SCSS Styles',
				'name' => 'rhino_enable_sassify',
				'type' => 'true_false',
				'instructions' => 'Checking this box will load an upgraded set of styles for enhanced Event views and responsive layouts.	May not be compatible with your current site design, use with caution.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55c10c5085bc0',
				'label' => 'Layout Width',
				'name' => 'rhino_layout_width',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'980px' => '980px',
					'1140px' => '1140px',
					'1280px' => '1280px',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e0b18513e9d',
				'label' => 'Float Navigation Right',
				'name' => 'rhino_navigation_position',
				'type' => 'radio',
				'choices' => array (
					'below' => 'No',
					'inside' => 'Yes',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'below',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_56031605e9320',
				'label' => 'Sticky Navigation Bar',
				'name' => 'rhino_sticky_navigation',
				'type' => 'radio',
				'choices' => array (
					'false' => 'No',
					'true' => 'Yes',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'false',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_55e0ba552b2a8',
				'label' => 'Homepage Slider Layout',
				'name' => 'rhino_slider_layout',
				'type' => 'radio',
				'choices' => array (
					'bottom' => 'Bottom Info Overlay',
					'thumbnails' => 'Thumbnail View',
					'left' => 'Left Info Overlay',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'bottom',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5643bc5f3f5f2',
				'label' => 'Thumbnail Slides Info',
				'name' => '',
				'type' => 'message',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e0ba552b2a8',
							'operator' => '==',
							'value' => 'thumbnails',
						),
					),
					'allorany' => 'all',
				),
				'message' => '<strong>Thumbnail View Tip!</strong><br/>Ensure that the <a href="/wp-admin/edit.php?post_type=slide&page=slides_settings">Slider Navigation</a> is set to either Paged or Both in order to display Thumbnails.',
			),
			array (
				'key' => 'field_55ce488021df8',
				'label' => 'Background Images Description',
				'name' => '',
				'type' => 'message',
				'message' => '<h3>Site Background image</h3>
	Background images will repeat automatically. We recommend using subtle patterns rather than large images. If you would like to style them differently, refer to <a href="http://www.w3schools.com/css/css3_backgrounds.asp" target="_blank">this link</a> for direction.',
			),
			array (
				'key' => 'field_55ce3fc8e874d',
				'label' => 'Body Background Image',
				'name' => 'rhino_bg_body_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55ce49b0f538d',
				'label' => 'Body Background Repeat',
				'name' => 'rhino_bg_body_repeat',
				'type' => 'select',
				'choices' => array (
					'no-repeat' => 'No Repeat',
					'repeat' => 'Repeat',
					'repeat-x' => 'Repeat Horizontally',
					'repeat-y' => 'Repeat Vertically',
				),
				'default_value' => 'no-repeat',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55ce4a0bf5390',
				'label' => 'Body Background Size',
				'name' => 'rhino_bg_body_size',
				'type' => 'select',
				'choices' => array (
					'auto' => 'Auto',
					'cover' => 'Cover',
					'contain' => 'Contain',
				),
				'default_value' => 'auto : Auto',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55c8f41f3bb7c',
				'label' => 'Header & Footer',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55c9094f2dcfb',
				'label' => 'Header Logo',
				'name' => 'rhino_header_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_55c909652dcfd',
				'label' => 'Favicon',
				'name' => 'rhino_favicon',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55c9095a2dcfc',
				'label' => 'Footer Logo',
				'name' => 'rhino_footer_logo',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_55ce3f943ecdc',
				'label' => 'Header Background Image',
				'name' => 'rhino_bg_header_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55ce49e5f538e',
				'label' => 'Header Background Repeat',
				'name' => 'rhino_bg_header_repeat',
				'type' => 'select',
				'choices' => array (
					'no-repeat' => 'No Repeat',
					'repeat' => 'Repeat',
					'repeat-x' => 'Repeat Horizontally',
					'repeat-y' => 'Repeat Vertically',
				),
				'default_value' => 'no-repeat',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55ce4a39f5391',
				'label' => 'Header Background Size',
				'name' => 'rhino_bg_header_size',
				'type' => 'select',
				'choices' => array (
					'auto' => 'Auto',
					'cover' => 'Cover',
					'contain' => 'Contain',
				),
				'default_value' => 'auto : Auto',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55ce3fa13ecdd',
				'label' => 'Footer Background Image',
				'name' => 'rhino_bg_footer_img',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55ce49f2f538f',
				'label' => 'Footer Background Repeat',
				'name' => 'rhino_bg_footer_repeat',
				'type' => 'select',
				'choices' => array (
					'no-repeat' => 'No Repeat',
					'repeat' => 'Repeat',
					'repeat-x' => 'Repeat Horizontally',
					'repeat-y' => 'Repeat Vertically',
				),
				'default_value' => 'no-repeat',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55ce4a4af5392',
				'label' => 'Footer Background Size',
				'name' => 'rhino_bg_footer_size',
				'type' => 'select',
				'choices' => array (
					'auto' => 'Auto',
					'cover' => 'Cover',
					'contain' => 'Contain',
				),
				'default_value' => 'auto : Auto',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e0becc7dd33',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'message' => 'The following fields are used to generate the contact info and social icons in both the header and footer.',
			),
			array (
				'key' => 'field_55c8f42a3bb7d',
				'label' => 'Address',
				'name' => 'rhino_contact_address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8f43e3bb7e',
				'label' => 'Address Link',
				'name' => 'rhino_contact_address_link',
				'type' => 'text',
				'instructions' => 'Link to Google Map page',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8f44c3bb7f',
				'label' => 'Phone Number',
				'name' => 'rhino_contact_phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5601ac10ddf6e',
				'label' => 'Email Address',
				'name' => 'rhino_contact_email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8ff405b642',
				'label' => 'Facebook',
				'name' => 'rhino_contact_facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8ff4a5b643',
				'label' => 'Twitter',
				'name' => 'rhino_contact_twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8ff545b644',
				'label' => 'Google +',
				'name' => 'rhino_contact_googleplus',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8f792bcac7',
				'label' => 'Instagram',
				'name' => 'rhino_contact_instagram',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8ffea5b647',
				'label' => 'Pinterest',
				'name' => 'rhino_contact_pinterest',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8ff695b646',
				'label' => 'Flickr',
				'name' => 'rhino_contact_flickr',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8fff45b648',
				'label' => 'Tumblr',
				'name' => 'rhino_contact_tumblr',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c8fffe5b649',
				'label' => 'Youtube',
				'name' => 'rhino_contact_youtube',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c900085b64a',
				'label' => 'Spotify',
				'name' => 'rhino_contact_spotify',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55c0fa429e536',
				'label' => 'Typography',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_55c0fa869e065',
				'label' => 'Body Font Family',
				'name' => 'rhino_body_font_family',
				'type' => 'google_font_selector',
				'include_web_safe_fonts' => 1,
				'enqueue_font' => 1,
				'default_font' => 'Droid Sans',
			),
			array (
				'key' => 'field_55c0fa709e064',
				'label' => 'Header Font Family',
				'name' => 'rhino_header_font_family',
				'type' => 'google_font_selector',
				'include_web_safe_fonts' => 1,
				'enqueue_font' => 1,
				'default_font' => 'Droid Sans',
			),
			array (
				'key' => 'field_55c0fa909e066',
				'label' => 'Call to Action Font Family',
				'name' => 'rhino_cta_font_family',
				'type' => 'google_font_selector',
				'include_web_safe_fonts' => 1,
				'enqueue_font' => 1,
				'default_font' => 'Droid Sans',
			),
			array (
				'key' => 'field_55c0f7369e523',
				'label' => 'Colors',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_564a070255886',
				'label' => 'Enable Advanced Color Controls',
				'name' => 'rhino_advanced_color_controls',
				'type' => 'true_false',
				'instructions' => 'This site is equipped with a dynamic color scheme generation system.	Turning on this feature may override style and settings on older sites, which may result in unexpected changes.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55c0f74e9e524',
				'label' => 'Primary Color',
				'name' => 'rhino_primary_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_564a070255886',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#ABBB00',
			),
			array (
				'key' => 'field_55c0f7589e525',
				'label' => 'Secondary Color',
				'name' => 'rhino_secondary_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_564a070255886',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#232409',
			),
			array (
				'key' => 'field_55c0f7609e526',
				'label' => 'Tertiary Color',
				'name' => 'rhino_tertiary_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_564a070255886',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#FCFEEC',
			),
			array (
				'key' => 'field_55c0f82c9e52e',
				'label' => 'Link Color',
				'name' => 'rhino_link_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_564a070255886',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#ABBB00',
			),
			array (
				'key' => 'field_55c0f8589e530',
				'label' => 'Primary CTA Button Color',
				'name' => 'rhino_button_primary_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_564a070255886',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '#FE5D26',
			),
			array (
				'key' => 'field_55ce453824ec2',
				'label' => 'Special Features',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_564a3534b8f69',
				'label' => 'CTA Button Rounding',
				'name' => 'rhino_button_radius',
				'type' => 'select',
				'choices' => array (
					'0px' => 'None',
					'1px' => '1px',
					'2px' => '2px',
					'3px' => '3px',
					'4px' => '4px',
					'5px' => '5px',
				),
				'default_value' => 'none',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56098d8ad2b79',
				'label' => 'Default Event Image',
				'name' => 'rhino_event_image',
				'type' => 'image',
				'instructions' => 'When this is set the image indicated will be used in all Event Listings when a Featured Image is not set.	 A square image ratio is recommended.',
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_56098e21d2b7a',
				'label' => 'AddThis Publisher ID',
				'name' => 'rhino_addthis_publisher_id',
				'type' => 'text',
				'instructions' => 'Set the Publisher ID for <a href="http://www.addthis.com/" target="_blank">AddThis</a> social tools.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56098f76d2b7b',
				'label' => 'Yoast Events Archive Title',
				'name' => 'yoast_seo_events_title',
				'type' => 'text',
				'instructions' => 'This is sent to the Yoast SEO plugin when building the Title for the Events Archive (/events/) page.	This will override other settings in Yoast.

	You can find a complete list of Yoast\'s <a href="http://kb.yoast.com/article/146-yoast-wordpress-seo-titles-metas-template-variables#basic-variables" target="_blank">supported variables here</a>.',
				'default_value' => 'Upcoming Events %%sep%% %%sitename%%',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5609951f05650',
				'label' => 'Tabbed Widgets on Homepage',
				'name' => 'tabbed_widgets_on_homepage',
				'type' => 'true_false',
				'instructions' => 'When enable this will cause all separate widgets in the Homepage Content widget area to be displayed in a single tabbed panel.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_56099ada43ccf',
				'label' => '404 Page Title',
				'name' => 'rhino_404_title',
				'type' => 'text',
				'default_value' => 'Oops!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5609957505651',
				'label' => '404 Page Content',
				'name' => 'rhino_404_content',
				'type' => 'wysiwyg',
				'instructions' => 'This content is displayed on 404 pages above a list of upcoming events.',
				'default_value' => 'You may have clicked a link that is inactive or we led you astray. Never fear! Use the menu above to find what you are looking for, or you can view events by starting below.',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-site-styles',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

