<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `wp_rhprhino`
//

// `wp_rhprhino`.`wp_options`
$wp_options = array(
  array('option_name' => 'woo_header_full_width','option_value' => 'true'),
  array('option_name' => 'woo_footer_full_width','option_value' => 'true'),
  array('option_name' => 'woo_footer_left','option_value' => 'false'),
  array('option_name' => 'woo_footer_right','option_value' => 'false'),
  array('option_name' => 'woothemes_helper_dismiss_activation_notice','option_value' => '1'),
  array('option_name' => 'woo_layout_width','option_value' => '1140'),
  array('option_name' => 'woo_layout','option_value' => 'two-col-left'),
  array('option_name' => 'woo_footer_sidebars','option_value' => '4'),
  array('option_name' => 'rhino_body_font','option_value' => 'a:5:{s:4:"size";s:2:"14";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Code Pro";s:5:"style";s:3:"300";s:5:"color";s:7:"#000000";}'),
  array('option_name' => 'rhino_header_font','option_value' => 'a:5:{s:4:"size";s:1:"9";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Code Pro";s:5:"style";s:3:"300";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_uppercase_headers','option_value' => 'true'),
  array('option_name' => 'rhino_button_font','option_value' => 'a:5:{s:4:"size";s:1:"9";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Code Pro";s:5:"style";s:3:"300";s:5:"color";s:7:"#000000";}'),
  array('option_name' => 'woo_link_color','option_value' => '#24227f'),
  array('option_name' => 'woo_link_hover_color','option_value' => '#181755'),
  array('option_name' => 'woo_font_h1','option_value' => '#000000'),
  array('option_name' => 'woo_font_h2','option_value' => '#000000'),
  array('option_name' => 'woo_font_h3','option_value' => '#000000'),
  array('option_name' => 'woo_font_h4','option_value' => '#000000'),
  array('option_name' => 'woo_font_h5','option_value' => '#000000'),
  array('option_name' => 'woo_font_h6','option_value' => '#000000'),
  array('option_name' => 'rhino_uppercase_cta','option_value' => 'true'),
  array('option_name' => 'woo_style_bg','option_value' => '#ffffff'),
  array('option_name' => 'woo_border_top','option_value' => 'a:3:{s:5:"width";s:1:"5";s:5:"style";s:5:"solid";s:5:"color";s:7:"#000000";}'),
  array('option_name' => 'woo_style_border','option_value' => ''),
  array('option_name' => 'rhino_button_rounded_corners','option_value' => ''),
  array('option_name' => 'rhino_cta_primary_button_background_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_cta_primary_button_hover_background_color','option_value' => '#bfaf00'),
  array('option_name' => 'rhino_cta_primary_button_font_color','option_value' => '#000000'),
  array('option_name' => 'rhino_cta_secondary_button_background_color','option_value' => '#000000'),
  array('option_name' => 'rhino_cta_secondary_button_hover_background_color','option_value' => '#494949'),
  array('option_name' => 'rhino_cta_secondary_button_font_color','option_value' => '#ffffff'),
  array('option_name' => 'rhino_cta_tertiary_button_background_color','option_value' => '#cccccc'),
  array('option_name' => 'rhino_cta_tertiary_button_font_color','option_value' => '#ffffff'),
  array('option_name' => 'rhino_nav_location','option_value' => 'inside'),
  array('option_name' => 'woo_nav_bg','option_value' => ''),
  array('option_name' => 'woo_top_nav_bg','option_value' => ''),
  array('option_name' => 'woo_nav_font','option_value' => '#000000'),
  array('option_name' => 'woo_nav_hover_bg','option_value' => '#fde700'),
  array('option_name' => 'rhino_submenu_bg_color','option_value' => '#fde700'),
  array('option_name' => 'rhino_submenu_hover_bg_color','option_value' => '#bfaf00'),
  array('option_name' => 'woo_nav_dropdown_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_nav_divider_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_nav_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_nav_border_bot','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_nav_border_lr','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_nav_margin_top','option_value' => ''),
  array('option_name' => 'woo_nav_margin_bottom','option_value' => ''),
  array('option_name' => 'rhino_nav_sticky','option_value' => 'false'),
  array('option_name' => 'rhino_slider_layout','option_value' => 'bottom'),
  array('option_name' => 'rhino_slide_background_color','option_value' => '#000000'),
  array('option_name' => 'rhino_slide_font','option_value' => '#ffffff'),
  array('option_name' => 'rhino_slide_hover_font','option_value' => '#fde72f'),
  array('option_name' => 'rhino_slide_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_right','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_left','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_footer_bg','option_value' => '#000000'),
  array('option_name' => 'woo_footer_full_width_bg','option_value' => '#000000'),
  array('option_name' => 'woo_foot_full_width_widget_bg','option_value' => '#000000'),
  array('option_name' => 'woo_footer_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#dbdbdb";}'),
  array('option_name' => 'woo_footer_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_footer_border_lr','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_footer_contact_info_font','option_value' => '#ffffff'),
  array('option_name' => 'rhino_footer_contact_info_link_hover_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_footer_social_icon_size','option_value' => '18'),
  array('option_name' => 'rhino_footer_social_icon_color','option_value' => '#ffffff'),
  array('option_name' => 'rhino_footer_social_icon_hover_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_rhp_logo_dark','option_value' => 'false'),
  array('option_name' => 'rhino_tribe_override_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_events_box_background','option_value' => '#ffffff'),
  array('option_name' => 'rhino_events_header_font','option_value' => '#000000'),
  array('option_name' => 'rhino_events_header_font_hover_color','option_value' => ''),
  array('option_name' => 'rhino_events_tagline_font','option_value' => '#000000'),
  array('option_name' => 'rhino_events_subheader_font','option_value' => '#000000'),
  array('option_name' => 'rhino_events_details_font','option_value' => '#000000'),
  array('option_name' => 'rhino_share_font','option_value' => '#000000'),
  array('option_name' => 'rhino_events_box_bottom_border','option_value' => 'a:3:{s:5:"width";s:1:"5";s:5:"style";s:5:"solid";s:5:"color";s:7:"#000000";}'),
  array('option_name' => 'rhino_events_box_rounded_corners','option_value' => ''),
  array('option_name' => 'rhino_datebox_rounded_corners','option_value' => ''),
  array('option_name' => 'rhino_datebox_month_background_color','option_value' => '#000000'),
  array('option_name' => 'rhino_datebox_month_font','option_value' => '#ffffff'),
  array('option_name' => 'rhino_datebox_date_background_color','option_value' => '#000000'),
  array('option_name' => 'rhino_datebox_date_font','option_value' => '#ffffff'),
  array('option_name' => 'rhino_datebox_day_background_color','option_value' => '#000000'),
  array('option_name' => 'rhino_datebox_day_font','option_value' => '#ffffff'),
  array('option_name' => 'rhino_events_listing_title','option_value' => ''),
  array('option_name' => 'rhino_homepage_title_text','option_value' => 'Upcoming Events'),
  array('option_name' => 'rhino_events_homepage_number','option_value' => '5'),
  array('option_name' => 'rhino_subnav_hover','option_value' => ''),
  array('option_name' => 'rhino_subnav_hover_bg','option_value' => ''),
  array('option_name' => 'woo_font_post_meta','option_value' => 'Array'),
  array('option_name' => 'woo_font_post_text','option_value' => 'Array'),
  array('option_name' => 'woo_font_post_more','option_value' => 'Array'),
  array('option_name' => 'woo_pagenav_font','option_value' => 'Array'),
  array('option_name' => 'woo_archive_header_font','option_value' => 'Array'),
  array('option_name' => 'woo_post_more_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_post_more_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_post_author_bg','option_value' => '#fafafa'),
  array('option_name' => 'woo_post_author_border_top','option_value' => 'a:3:{s:5:"width";s:1:"1";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_post_author_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"1";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_post_author_border_lr','option_value' => 'a:3:{s:5:"width";s:1:"1";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_post_author_border_radius','option_value' => '5px'),
  array('option_name' => 'woo_post_comments_bg','option_value' => ''),
  array('option_name' => 'woo_pagenav_bg','option_value' => ''),
  array('option_name' => 'woo_pagenav_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_pagenav_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_archive_header_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"1";s:5:"style";s:5:"solid";s:5:"color";s:7:"#e6e6e6";}'),
  array('option_name' => 'woo_archive_header_disable_rss','option_value' => 'false'),
  array('option_name' => 'woo_widget_bg','option_value' => '#efefef'),
  array('option_name' => 'woo_widget_font_text','option_value' => '#000000'),
  array('option_name' => 'woo_widget_font_text-1','option_value' => '#000000'),
  array('option_name' => 'woo_widget_title_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_widget_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_widget_padding_tb','option_value' => ''),
  array('option_name' => 'woo_widget_padding_lr','option_value' => ''),
  array('option_name' => 'woo_widget_border_radius','option_value' => '0px'),
  array('option_name' => 'rhino_email_background_color','option_value' => '#efefef'),
  array('option_name' => 'rhino_email_header_font','option_value' => '#000000'),
  array('option_name' => 'rhino_email_details_font','option_value' => '#000000'),
  array('option_name' => 'rhino_email_input_font','option_value' => '#000000'),
  array('option_name' => 'rhino_email_top_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_email_bottom_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_email_side_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_header_bg','option_value' => ''),
  array('option_name' => 'woo_full_header_full_width_bg','option_value' => ''),
  array('option_name' => 'woo_header_margin_top','option_value' => '0'),
  array('option_name' => 'woo_header_margin_bottom','option_value' => '0'),
  array('option_name' => 'woo_header_padding_top','option_value' => '40'),
  array('option_name' => 'woo_header_padding_bottom','option_value' => '40'),
  array('option_name' => 'woo_header_padding_left','option_value' => ''),
  array('option_name' => 'woo_header_padding_right','option_value' => ''),
  array('option_name' => 'woo_header_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_right','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_left','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_contact_info_font','option_value' => '#000000'),
  array('option_name' => 'rhino_header_contact_info_link_hover_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_header_social_icon_size','option_value' => '18'),
  array('option_name' => 'rhino_header_social_icon_color','option_value' => '#000000'),
  array('option_name' => 'rhino_header_social_icon_hover_color','option_value' => '#fde72f'),
  array('option_name' => 'rhino_timezone','option_value' => 'a:2:{s:2:"wp";s:1:"0";s:5:"dtzid";s:15:"Atlantic/Azores";}')
);
