<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `wp_rhprhino`
//

// `wp_rhprhino`.`wp_options`
$wp_options = array(
  array('option_name' => 'rhino_body_font','option_value' => 'a:5:{s:4:"size";s:2:"14";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Sans Pro";s:5:"style";s:3:"300";s:5:"color";s:7:"#252627";}'),
  array('option_name' => 'rhino_button_font','option_value' => 'a:5:{s:4:"size";s:1:"9";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Sans Pro";s:5:"style";s:3:"300";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_button_rounded_corners','option_value' => '5'),
  array('option_name' => 'rhino_cta_primary_button_background_color','option_value' => '#bb0a21'),
  array('option_name' => 'rhino_cta_primary_button_font_color','option_value' => '#fffff9'),
  array('option_name' => 'rhino_cta_primary_button_hover_background_color','option_value' => '#630512'),
  array('option_name' => 'rhino_cta_secondary_button_background_color','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_cta_secondary_button_font_color','option_value' => '#fffff9'),
  array('option_name' => 'rhino_cta_secondary_button_hover_background_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_cta_tertiary_button_background_color','option_value' => '#e7e8ed'),
  array('option_name' => 'rhino_cta_tertiary_button_font_color','option_value' => '#fffff9'),
  array('option_name' => 'rhino_datebox_date_background_color','option_value' => '#252627'),
  array('option_name' => 'rhino_datebox_date_font','option_value' => '#fffff9'),
  array('option_name' => 'rhino_datebox_day_background_color','option_value' => '#252627'),
  array('option_name' => 'rhino_datebox_day_font','option_value' => '#fffff9'),
  array('option_name' => 'rhino_datebox_month_background_color','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_datebox_month_font','option_value' => '#fffff9'),
  array('option_name' => 'rhino_datebox_rounded_corners','option_value' => '5'),
  array('option_name' => 'rhino_email_background_color','option_value' => '#252627'),
  array('option_name' => 'rhino_email_bottom_border','option_value' => 'a:3:{s:5:"width";s:1:"5";s:5:"style";s:5:"solid";s:5:"color";s:7:"#4b88a2";}'),
  array('option_name' => 'rhino_email_details_font','option_value' => '#fff9fb'),
  array('option_name' => 'rhino_email_header_font','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_email_input_font','option_value' => '#252627'),
  array('option_name' => 'rhino_email_side_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_email_top_border','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_events_box_background','option_value' => '#e7e8ed'),
  array('option_name' => 'rhino_events_box_bottom_border','option_value' => 'a:3:{s:5:"width";s:1:"5";s:5:"style";s:5:"solid";s:5:"color";s:7:"#4b88a2";}'),
  array('option_name' => 'rhino_events_box_rounded_corners','option_value' => '5'),
  array('option_name' => 'rhino_events_details_font','option_value' => '#252627'),
  array('option_name' => 'rhino_events_header_font','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_events_header_font_hover_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_events_subheader_font','option_value' => '#252627'),
  array('option_name' => 'rhino_events_tagline_font','option_value' => '#252627'),
  array('option_name' => 'rhino_footer_contact_info_font','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_footer_contact_info_link_hover_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_footer_social_icon_color','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_footer_social_icon_hover_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_footer_social_icon_size','option_value' => '16'),
  array('option_name' => 'rhino_header_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_contact_info_font','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_header_contact_info_link_hover_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_header_font','option_value' => 'a:5:{s:4:"size";s:1:"9";s:4:"unit";s:2:"px";s:4:"face";s:15:"Source Sans Pro";s:5:"style";s:3:"300";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_left','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_right','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_header_social_icon_color','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_header_social_icon_hover_color','option_value' => '#223f4a'),
  array('option_name' => 'rhino_header_social_icon_size','option_value' => '16'),
  array('option_name' => 'rhino_nav_location','option_value' => 'inside'),
  array('option_name' => 'rhino_nav_sticky','option_value' => 'false'),
  array('option_name' => 'rhino_rhp_logo_dark','option_value' => 'false'),
  array('option_name' => 'rhino_share_font','option_value' => '#252627'),
  array('option_name' => 'rhino_slide_background_color','option_value' => '#252627'),
  array('option_name' => 'rhino_slide_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_left','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_right','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'rhino_slide_font','option_value' => '#fffff9'),
  array('option_name' => 'rhino_slide_hover_font','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_slider_layout','option_value' => 'bottom'),
  array('option_name' => 'rhino_submenu_bg_color','option_value' => '#fffff9'),
  array('option_name' => 'rhino_submenu_hover_bg_color','option_value' => '#959699'),
  array('option_name' => 'rhino_tribe_override_color','option_value' => '#4b88a2'),
  array('option_name' => 'rhino_uppercase_cta','option_value' => 'false'),
  array('option_name' => 'rhino_uppercase_headers','option_value' => 'false'),
  array('option_name' => 'woo_border_top','option_value' => 'a:3:{s:5:"width";s:1:"5";s:5:"style";s:5:"solid";s:5:"color";s:7:"#4b88a2";}'),
  array('option_name' => 'woo_disable_post_author','option_value' => 'true'),
  array('option_name' => 'woo_font_h1','option_value' => '#252627'),
  array('option_name' => 'woo_font_h2','option_value' => '#252627'),
  array('option_name' => 'woo_font_h3','option_value' => '#252627'),
  array('option_name' => 'woo_font_h4','option_value' => '#252627'),
  array('option_name' => 'woo_font_h5','option_value' => '#252627'),
  array('option_name' => 'woo_font_h6','option_value' => '#252627'),
  array('option_name' => 'woo_foot_full_width_widget_bg','option_value' => '#e7e8ed'),
  array('option_name' => 'woo_footer_bg','option_value' => '#252627'),
  array('option_name' => 'woo_footer_border_bottom','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_footer_border_lr','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_footer_border_top','option_value' => 'a:3:{s:5:"width";s:1:"0";s:5:"style";s:5:"solid";s:5:"color";s:0:"";}'),
  array('option_name' => 'woo_footer_full_width','option_value' => 'true'),
  array('option_name' => 'woo_footer_full_width_bg','option_value' => '#252627'),
  array('option_name' => 'woo_footer_left','option_value' => 'false'),
  array('option_name' => 'woo_footer_right','option_value' => 'false')
);
